enum ClHtml {
    about = 'ph ph-question',
    check = 'ph ph-check',
    cross = 'ph ph-x',
    wrenchF = 'ph ph-wrench',
    envelope = 'ph ph-envelope',
    caretRB = 'ph ph-caret-right',
    caretLB = 'ph ph-caret-left',
    caretNB = 'ph ph-caret-up-down',
    caretDB = 'ph ph-caret-down',
    caretUB = 'ph ph-caret-up',
    downlF = 'ph ph-file-arrow-down',
    clipB = 'ph ph-clipboard-text',
    search = 'ph ph-magnifying-glass',
    book = 'ph ph-book',
    term = 'ph ph-terminal-window',
    news = 'ph ph-newspaper',
    team = 'ph ph-users-three',
    user = 'ph ph-user',
    cont = 'ph ph-shipping-container',
    filter = 'ph ph-funnel',
    youtube = 'ph ph-youtube-logo',
    blueS = 'ph ph-butterfly',
    linkedIn = 'ph ph-linkedin-logo',
    per = 'ph ph-person-simple',
    reg = 'ph ph-certificate',
    undDep = 'ph ph-clock-countdown',
    depOn = 'ph ph-check-circle',
    depOff = 'ph ph-x-circle',
}
export default ClHtml;
