# SPDX-FileCopyrightText: 2026 Artur Lissin, Leibniz Institute DSMZ-German Collection of Microorganisms and Cell Cultures GmbH
#
# SPDX-License-Identifier: CC0-1.0

services:
    app_dev:
        user: devu
        env_file:
            - .env
        environment:
            HISTFILE: /dev/null
            HISTSIZE: 0
            HISTFILESIZE: 0
        build:
            context: .
            dockerfile: ./configs/docker/dev.Dockerfile
            args:
                USERNAME: devu
                USER_UID: 1000
                USER_GID: 1000
                WORK_DIR: /workspace
                BIN_DEPLOY_PREP: ${BIN_DEPLOY_PREP}
                BIN_DEPLOY_REQ: ${BIN_DEPLOY_REQ}
                SSH_AUTH_SOCK: /ssh-agent
                GITCONFIG_PATH: ${GITCONFIG_PATH}
        volumes:
            - ${SSH_AUTH_SOCK:-/dev/null}:/ssh-agent
            - .:/workspace
            - ${GITCONFIG_PATH:-${HOME}/.gitconfig}:/etc/gitconfig:ro
            - redis-sock:/redis
            - mariadb-sock:/mariadb
        ports:
            - ${BACKEND_DEV_PORT}:${BACKEND_DEV_PORT}
            - ${BACKEND_STAGE_PORT}:${BACKEND_STAGE_PORT}
            - ${FRONTEND_DEV_PORT}:${FRONTEND_DEV_PORT}
            - ${FRONTEND_STAGE_PORT}:${FRONTEND_STAGE_PORT}
        networks:
            - straininfo
            - ollama

networks:
    ollama:
        name: ollama
        driver: bridge
