# SPDX-FileCopyrightText: 2026 Artur Lissin, Leibniz Institute DSMZ-German Collection of Microorganisms and Cell Cultures GmbH
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = ["prompt/**/*.md"]
precedence = "override"
SPDX-FileCopyrightText = "2026 Artur Lissin, Leibniz Institute DSMZ-German Collection of Microorganisms and Cell Cultures GmbH"
SPDX-License-Identifier = "CC-BY-4.0"
