// SPDX-FileCopyrightText: 2026 Artur Lissin, Leibniz Institute DSMZ-German Collection of Microorganisms and Cell Cultures GmbH
//
// SPDX-License-Identifier: MIT

enum Col {
    col = 'col',
    lAuto = 'col-lg-auto',
    lN1 = 'col-lg-1',
    lN2 = 'col-lg-2',
    lN9 = 'col-lg-9',
    lN3 = 'col-lg-3',
    lN4 = 'col-lg-4',
    lN8 = 'col-lg-8',
    lN7 = 'col-lg-7',
    lN6 = 'col-lg-6',
    lN10 = 'col-lg-10',
    lN11 = 'col-lg-11',
    lN12 = 'col-lg-12',
    sN4 = 'col-sm-4',
    sN6 = 'col-sm-6',
    mN4 = 'col-md-4',
}

enum Dis {
    dBL = 'd-lg-block',
    dIFL = 'd-lg-inline-flex',
    dBM = 'd-md-block',
    dBS = 'd-sm-block',
    dNone = 'd-none',
    dIFlex = 'd-inline-flex',
    dFlex = 'd-flex',
    dBlock = 'd-block',
}

enum Mar {
    bNAT = 'mb-auto',
    bN15 = 'mb-15',
    bN10 = 'mb-10',
    bN5 = 'mb-5',
    N20 = 'm-20',
    N10 = 'm-10',
    N0 = 'm-0',
    lNAT = 'ml-auto',
    lN20 = 'ml-20',
    lN15 = 'ml-15',
    lN10 = 'ml-10',
    lN5 = 'ml-5',
    lN0 = 'ml-0',
    rN0 = 'mr-0',
    rN10 = 'mr-10',
    rNAT = 'mr-auto',
    tN15 = 'mt-15',
    tN10 = 'mt-10',
    tN0 = 'mt-0',
    tN5 = 'mt-5',
    yN5 = 'my-5',
    xN5 = 'mx-5',
}

enum Pad {
    N0 = 'p-0',
    N5 = 'p-5',
    N15 = 'p-15',
    bN0 = 'pb-0',
    bN10 = 'pb-10',
    bN15 = 'pb-15',
    bN5 = 'pb-5',
    tN0 = 'pt-0',
    tN5 = 'pt-5',
    tN15 = 'pt-15',
    lN0 = 'pl-0',
    lN10 = 'pl-10',
    lN15 = 'pl-15',
    rN10 = 'pr-10',
    rN5 = 'pr-5',
}

enum BgCol {
    prim = 'bg-primary',
    lMut = 'bg-header',
}

enum Tex {
    w = 'text-white',
    m = 'text-muted',
    p = 'text-primary',
    tr = 'text-truncate',
    tw = 'text-wrap',
    al = 'text-left',
    s = 'text-success',
    f = 'text-danger',
    sig = 'text-signal',
    break = 'text-break',
}

enum Align {
    jc = 'justify-content-center',
    je = 'justify-content-end',
    js = 'justify-content-start',
    ja = 'justify-content-around',
    jb = 'justify-content-between',
    fc = 'flex-column',
    fr = 'flex-row',
    fe = 'flex-end',
    ac = 'align-items-center',
}

enum Wid {
    f = 'w-full',
    a = 'w-auto',
    N500 = 'w-500',
    N600 = 'w-600',
    N100 = 'w-100',
    N150 = 'w-150',
    N50 = 'w-50',
    N25 = 'w-25',
    N300 = 'w-300',
    N250 = 'w-250',
    N200 = 'w-200',
    SMF = 'w-sm-full',
    MD400 = 'w-md-400',
    SM500 = 'w-sm-500',
    SM250 = 'w-sm-250',
    SM150 = 'w-sm-150',
    SM300 = 'w-sm-300',
}

enum Hei {
    f = 'h-full',
    N500 = 'h-500',
    N150 = 'h-150',
    N100 = 'h-100',
    N50 = 'h-50',
    N25 = 'h-25',
    h = 'h-half',
}

enum DdM {
    sug = 'suggestions',
    div = 'suggestions on-focus',
    t = 'text-muted',
    r = 'float-right text-primary',
    tl = 'float-left text-muted',
}

enum Font {
    bold = 'font-weight-bold',
    semBold = 'font-weight-semi-bold',
    norm = 'font-weight-normal',
    ita = 'font-italic',
    N12 = 'font-size-12',
    N18 = 'font-size-18',
}

enum ZInd {
    N10 = 'z-10',
}

enum ClHtml {
    cir = 'circle',
    sqr = 'square',
    al = 'alert',
    lab = 'label',
    alSt = 'sticky-alerts',
    sideSM = 'sidebar-small',
    side = 'sidebar',
    sNav = 'sidebar-topnav',
    sMen = 'sidebar-menu',
    sOv = 'sidebar-overlay',
    nBt = 'border-top-0',
    nBb = 'border-bottom-0',
    pDiv = 'progress',
    pBar = 'progress-bar',
    hov = 'hover',
    act = 'active',
    show = 'show',
    close = 'close',
    fil = 'filled',
    dis = 'disabled',
    pri = 'primary',
    mut = 'muted',
    blo = 'block',
    dan = 'danger',
    suc = 'success',
    sig = 'signal',
    pBtn = 'direction',
    bad = 'badge',
    breadC = 'breadcrumb',
    lead = 'lead',
    load = 'loading',
    noCol = 'colorless',
    wIco = 'with-icon',
    sim = 'simple',
    lis = 'list',
    linPar = 'link-parade',
    pag = 'pagination',
    tab = 'table',
    sm = 'small',
    key = 'key',
    tils = 'tiles',
    til = 'tile',
    tLin = 'tile-link',
    foot = 'footer',
    pgFoot = 'page-footer',
    pgWr = 'page-wrapper',
    lgP = 'logo-parade',
    icon = 'icon',
    igp = 'input-group-append',
    ig = 'input-group',
    inv = 'is-invalid',
    tit = 'title',
    hidS = 'hide-small',
    titSec = 'section-title',
    titB = 'title-bar',
    sec = 'section',
    secD = 'section-dark',
    secI = 'section-image',
    her = 'hero',
    herB = 'hero-box',
    box = 'box',
    cnt = 'content',
    cntCon = 'content-container',
    con = 'container',
    cntWr = 'content-wrapper',
    row = 'row',
    rowEq = 'row-eq-spacing',
    link = 'link',
    formGr = 'form-group',
    formCtrl = 'form-control',
    drD = 'dropdown',
    drDM = 'dropdown-menu',
    drDC = 'dropdown-menu-center',
    head = 'header',
    acc = 'accessibility',
    cCh = 'custom-checkbox',
    srO = 'sr-only',
    btn = 'btn',
    btnAct = 'btn-action collapsible',
    micI = 'ph ph-microbes',
    strRegT = 'ph ph-flask-check',
    taxI = 'ph ph-taxonomy',
    unfI = 'ph ph-unfilter',
    noTra = 'without-transitions',
    tra = 'with-transitions',
    posRel = 'position-relative',
    pageNav = 'on-this-page-nav',
    navB = 'navbar',
    navS = 'nav-search',
    navBb = 'navbar-bottom',
    navBt = 'navbar-top',
    navBn = 'navbar-nav',
    navBbr = 'navbar-brand',
    req = 'required',
}

export { Align, BgCol, ClHtml, Col, DdM, Dis, Font, Hei, Mar, Pad, Tex, Wid, ZInd };
