# SPDX-FileCopyrightText: 2026 Artur Lissin, Leibniz Institute DSMZ-German Collection of Microorganisms and Cell Cultures GmbH
#
# SPDX-License-Identifier: CC0-1.0

name: main

on:
    pull_request:
    push:
        branches: [main]

jobs:
    lin_lint:
        strategy:
            fail-fast: false
        runs-on: ubuntu-latest
        env:
            PY_DIR: uv
            CU_HOME: /home/custom
        steps:
            - name: Set up Python 3.13
              uses: actions/setup-python@v6
              with:
                  python-version: '3.13'
            - name: Set up Node 24
              uses: actions/setup-node@v6
              with:
                  node-version: '24'
            - name: Setup PHP with PECL extension
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.5'
            - name: Checkout
              uses: actions/checkout@v7
              with:
                  fetch-depth: 0
            - name: Install dependencies
              run: |
                sudo mkdir -p $CU_HOME && sudo chown runner -R $CU_HOME
                sudo apt install -y libedit-dev curl make git-lfs
                curl -LsSf https://astral.sh/uv/install.sh | UV_INSTALL_DIR=$CU_HOME/$PY_DIR sh
                echo "$CU_HOME/$PY_DIR/bin" >> $GITHUB_PATH
                echo "$CU_HOME/$PY_DIR/shims" >> $GITHUB_PATH
            - name: lint and test
              run: |
                  export CONTAINER="container"
                  make dev
                  make runChecks
